sudo: true

services:
  - docker

os:
  - linux

before_script:
  - wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.tar.gz
  - tar xf hugo.tar.gz

script:
  - make build

deploy:
  provider: releases
  api_key:
    secure: fSkKTXD/XM/6c2RHpluDZ0RekRC1MXUYID28w3rEox6AM52vJkLCb3muf4BnbJwE49mtIMkzRQZ6e7R9A9Er5+XcEtw4bwcTjf/Ejrp7aj+8Qm3sDaT1DGXUMh5GlDUtRxdwtySdY84PgPscnxQ1YE9mBPbl8Y9j6IQZZihhHVnJm10mzZwvQIBFyJ6irVa7BI1X6tS1sVuJ1hkagPiSIHkn49egf1+Rksk2QTms5ZeaZyGcItuGng0yZJA9qd9RAyLvzbJBSa2W01YoZXEqX0yqw/OeGSSIkDLOr8ar4ZnPepoAT1a8MpQY/TyBf6OQ4CiykRp21lbvQh7BgwyaPLRnZIN6cLde7Z688pEfUz45LU5VROsFXlCJXS/WPbus+G1O4l349JNFm7vvwAjqTJotnbFF0JrV9XcDozHE9lE92iuZMVmyqbQBIhY2OLdoJjK+NDgM5et6W1fgn66PCz2CRitprrukElSggWiXmSiY/kzvYvqqDADg50MZsfEvxbCgZCPZg6dciyPPEm0l1chmYCjoNoKBm+xgv1skvdwocXGYB9gHI0ihloxBjGC75rKxVGG5IPKDHWdHdBA7trI2XvG0wQFzNZZzpAawNggetwJxNjpPu5/+4kusxVWmdi5Hdq9UtLBbgVyAk/6IjjfVxb3m14axYSCfu7FCajc=
  on:
    repo: moov-io/moov-io
    tags: true
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

notifications:
  slack:
    secure: sF3gHuJVkcxR2nFoS0TlDG18htbIFQ3t7zmzQYTENYc+JjxTeI+YZpFr1nsJDV/yM/cO4z1Y1Bfbvd57WmcTKCXvKco7ADDuybGu3RQO8fgRp8VoO/pH7qk8H8dHRNkdPtklyscNmqOXkeLWTgudsZFApcMFp6PTw3vpVC4VXrN/aHH3ddfAhNnYqEoMYagb1Oa8E0pxJaXT0Vv+7ORQk+KZDJNcEAHM/7jkaNG9ygfVXYpGEA85xYMokveNNs+e9WWeOpTFZS/O3sfljNs5n5FUD3mKjznOSoUDo1ZktTr5TTT4/2WaqADplqBbCEv09vjPJroY8bqhH1MyXkXT4Pr32FO94O9Ufi8FNlAAtoqFV9Cqn59DkpaF95Ak/ARDK1LdvT8niWcpazZUzpHZc2s/tkttZVQeQEkhx5CJAUZgy2+/gIAWeqwGgUk8RYIwXNYp0m93/hVcdNvvsVowrSJVRlhc38eqlHXP4U+LdlqdLaEucxwlbQPqbdSQdvAn5CUkRBpjjOew/dM/z825Cih1llPBiVFAyW9D2DHLxjqKTBtBe4oK5Ny5ghJP76nS9cjwG0wkJ89RwCc9AfNyAHz2oLgSArV0zuLOzqHzZD3Z9WsF+6Wnq4wcSirjNEfO4fYoq78Z57FLJOpJJ0fbkCBfUDU5nbsZ+5TeiQcXaqs=
