sudo: true
services:
- docker
os:
- linux
# - osx # TravisCI on OSX doesn't support docker yet
script:
- make build
deploy:
  provider: releases
  api_key:
    secure: fSkKTXD/XM/6c2RHpluDZ0RekRC1MXUYID28w3rEox6AM52vJkLCb3muf4BnbJwE49mtIMkzRQZ6e7R9A9Er5+XcEtw4bwcTjf/Ejrp7aj+8Qm3sDaT1DGXUMh5GlDUtRxdwtySdY84PgPscnxQ1YE9mBPbl8Y9j6IQZZihhHVnJm10mzZwvQIBFyJ6irVa7BI1X6tS1sVuJ1hkagPiSIHkn49egf1+Rksk2QTms5ZeaZyGcItuGng0yZJA9qd9RAyLvzbJBSa2W01YoZXEqX0yqw/OeGSSIkDLOr8ar4ZnPepoAT1a8MpQY/TyBf6OQ4CiykRp21lbvQh7BgwyaPLRnZIN6cLde7Z688pEfUz45LU5VROsFXlCJXS/WPbus+G1O4l349JNFm7vvwAjqTJotnbFF0JrV9XcDozHE9lE92iuZMVmyqbQBIhY2OLdoJjK+NDgM5et6W1fgn66PCz2CRitprrukElSggWiXmSiY/kzvYvqqDADg50MZsfEvxbCgZCPZg6dciyPPEm0l1chmYCjoNoKBm+xgv1skvdwocXGYB9gHI0ihloxBjGC75rKxVGG5IPKDHWdHdBA7trI2XvG0wQFzNZZzpAawNggetwJxNjpPu5/+4kusxVWmdi5Hdq9UtLBbgVyAk/6IjjfVxb3m14axYSCfu7FCajc=
  on:
    repo: moov-io/moov-io
    tags: true
    go: 1.12.x
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
