[build]
publish = "public"
command = "hugo"

[context.deploy-preview]
  command = "hugo --buildFuture"

[context.production.environment]
HUGO_VERSION = "0.74.3"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[[redirects]]
  from = "/watchman"
  to = "https://demo.moov.io/watchman/"

[[redirects]]
  from = "/soc2"
  to = "https://docs.moov.io/soc2/"
