################################# Default configuration ###################
baseURL = "https://moov.io"
title = "Moov | At The Core of Fintech"
theme = "moov"
disableHugoGeneratorInject=true
googleAnalytics = "UA-118148273-1"

############################# Default Parameters ##########################
[params]
description = "At the core of fintech. Opensource Cloud Native Core processing for Fintechs, Startups, Banks & Credit Unions "

